// SPDX-License-Identifier: GPL-3.0-or-later
#include "bethconv/record/conditions.hpp"

#include "bethconv/record/field_reader.hpp"

#include <algorithm>
#include <array>
#include <utility>

namespace bethconv::record {
namespace {

using P = ConditionParam;

/// Every Skyrim condition function, by index. Generated from xEdit's
/// wbConditionFunctions (wbDefinitionsTES5.pas, dev-4.1.6): every parameter
/// type from ptActor on is a FormID; ptReference and ptActor are `reference`,
/// ptPackage `package`.
constexpr ConditionFunction k_functions[] = {
    {0, "GetWantBlocking", P::none, P::none},
    {1, "GetDistance", P::reference, P::none},
    {5, "GetLocked", P::none, P::none},
    {6, "GetPos", P::integer, P::none},
    {8, "GetAngle", P::integer, P::none},
    {10, "GetStartingPos", P::integer, P::none},
    {11, "GetStartingAngle", P::integer, P::none},
    {12, "GetSecondsPassed", P::none, P::none},
    {14, "GetActorValue", P::integer, P::none},
    {18, "GetCurrentTime", P::none, P::none},
    {24, "GetScale", P::none, P::none},
    {25, "IsMoving", P::none, P::none},
    {26, "IsTurning", P::none, P::none},
    {27, "GetLineOfSight", P::reference, P::none},
    {32, "GetInSameCell", P::reference, P::none},
    {35, "GetDisabled", P::none, P::none},
    {36, "MenuMode", P::integer, P::none},
    {39, "GetDisease", P::none, P::none},
    {41, "GetClothingValue", P::none, P::none},
    {42, "SameFaction", P::reference, P::none},
    {43, "SameRace", P::reference, P::none},
    {44, "SameSex", P::reference, P::none},
    {45, "GetDetected", P::reference, P::none},
    {46, "GetDead", P::none, P::none},
    {47, "GetItemCount", P::form, P::none},
    {48, "GetGold", P::none, P::none},
    {49, "GetSleeping", P::none, P::none},
    {50, "GetTalkedToPC", P::none, P::none},
    {53, "GetScriptVariable", P::reference, P::string},
    {56, "GetQuestRunning", P::form, P::none},
    {58, "GetStage", P::form, P::none},
    {59, "GetStageDone", P::form, P::quest_stage},
    {60, "GetFactionRankDifference", P::form, P::reference},
    {61, "GetAlarmed", P::none, P::none},
    {62, "IsRaining", P::none, P::none},
    {63, "GetAttacked", P::none, P::none},
    {64, "GetIsCreature", P::none, P::none},
    {65, "GetLockLevel", P::none, P::none},
    {66, "GetShouldAttack", P::reference, P::none},
    {67, "GetInCell", P::form, P::none},
    {68, "GetIsClass", P::form, P::none},
    {69, "GetIsRace", P::form, P::none},
    {70, "GetIsSex", P::integer, P::none},
    {71, "GetInFaction", P::form, P::none},
    {72, "GetIsID", P::form, P::none},
    {73, "GetFactionRank", P::form, P::none},
    {74, "GetGlobalValue", P::form, P::none},
    {75, "IsSnowing", P::none, P::none},
    {77, "GetRandomPercent", P::none, P::none},
    {79, "GetQuestVariable", P::form, P::string},
    {80, "GetLevel", P::none, P::none},
    {81, "IsRotating", P::none, P::none},
    {84, "GetDeadCount", P::form, P::none},
    {91, "GetIsAlerted", P::none, P::none},
    {98, "GetPlayerControlsDisabled", P::integer, P::integer},
    {99, "GetHeadingAngle", P::reference, P::none},
    {101, "IsWeaponMagicOut", P::none, P::none},
    {102, "IsTorchOut", P::none, P::none},
    {103, "IsShieldOut", P::none, P::none},
    {106, "IsFacingUp", P::none, P::none},
    {107, "GetKnockedState", P::none, P::none},
    {108, "GetWeaponAnimType", P::none, P::none},
    {109, "IsWeaponSkillType", P::integer, P::none},
    {110, "GetCurrentAIPackage", P::none, P::none},
    {111, "IsWaiting", P::none, P::none},
    {112, "IsIdlePlaying", P::none, P::none},
    {116, "IsIntimidatedbyPlayer", P::none, P::none},
    {117, "IsPlayerInRegion", P::form, P::none},
    {118, "GetActorAggroRadiusViolated", P::none, P::none},
    {122, "GetCrime", P::reference, P::integer},
    {123, "IsGreetingPlayer", P::none, P::none},
    {125, "IsGuard", P::none, P::none},
    {127, "HasBeenEaten", P::none, P::none},
    {128, "GetStaminaPercentage", P::none, P::none},
    {129, "GetPCIsClass", P::form, P::none},
    {130, "GetPCIsRace", P::form, P::none},
    {131, "GetPCIsSex", P::integer, P::none},
    {132, "GetPCInFaction", P::form, P::none},
    {133, "SameFactionAsPC", P::none, P::none},
    {134, "SameRaceAsPC", P::none, P::none},
    {135, "SameSexAsPC", P::none, P::none},
    {136, "GetIsReference", P::reference, P::none},
    {141, "IsTalking", P::none, P::none},
    {142, "GetWalkSpeed", P::none, P::none},
    {143, "GetCurrentAIProcedure", P::none, P::none},
    {144, "GetTrespassWarningLevel", P::none, P::none},
    {145, "IsTrespassing", P::none, P::none},
    {146, "IsInMyOwnedCell", P::none, P::none},
    {147, "GetWindSpeed", P::none, P::none},
    {148, "GetCurrentWeatherPercent", P::none, P::none},
    {149, "GetIsCurrentWeather", P::form, P::none},
    {150, "IsContinuingPackagePCNear", P::none, P::none},
    {152, "GetIsCrimeFaction", P::form, P::none},
    {153, "CanHaveFlames", P::none, P::none},
    {154, "HasFlames", P::none, P::none},
    {157, "GetOpenState", P::none, P::none},
    {159, "GetSitting", P::none, P::none},
    {161, "GetIsCurrentPackage", P::package, P::none},
    {162, "IsCurrentFurnitureRef", P::reference, P::none},
    {163, "IsCurrentFurnitureObj", P::form, P::none},
    {170, "GetDayOfWeek", P::none, P::none},
    {172, "GetTalkedToPCParam", P::reference, P::none},
    {175, "IsPCSleeping", P::none, P::none},
    {176, "IsPCAMurderer", P::none, P::none},
    {180, "HasSameEditorLocAsRef", P::reference, P::form},
    {181, "HasSameEditorLocAsRefAlias", P::alias, P::form},
    {182, "GetEquipped", P::form, P::none},
    {185, "IsSwimming", P::none, P::none},
    {190, "GetAmountSoldStolen", P::none, P::none},
    {192, "GetIgnoreCrime", P::none, P::none},
    {193, "GetPCExpelled", P::form, P::none},
    {195, "GetPCFactionMurder", P::form, P::none},
    {197, "GetPCEnemyofFaction", P::form, P::none},
    {199, "GetPCFactionAttack", P::form, P::none},
    {203, "GetDestroyed", P::none, P::none},
    {214, "HasMagicEffect", P::form, P::none},
    {215, "GetDefaultOpen", P::none, P::none},
    {219, "GetAnimAction", P::none, P::none},
    {223, "IsSpellTarget", P::form, P::none},
    {224, "GetVATSMode", P::none, P::none},
    {225, "GetPersuasionNumber", P::none, P::none},
    {226, "GetVampireFeed", P::none, P::none},
    {227, "GetCannibal", P::none, P::none},
    {228, "GetIsClassDefault", P::form, P::none},
    {229, "GetClassDefaultMatch", P::none, P::none},
    {230, "GetInCellParam", P::form, P::reference},
    {235, "GetVatsTargetHeight", P::none, P::none},
    {237, "GetIsGhost", P::none, P::none},
    {242, "GetUnconscious", P::none, P::none},
    {244, "GetRestrained", P::none, P::none},
    {246, "GetIsUsedItem", P::form, P::none},
    {247, "GetIsUsedItemType", P::integer, P::none},
    {248, "IsScenePlaying", P::form, P::none},
    {249, "IsInDialogueWithPlayer", P::none, P::none},
    {250, "GetLocationCleared", P::form, P::none},
    {254, "GetIsPlayableRace", P::none, P::none},
    {255, "GetOffersServicesNow", P::none, P::none},
    {258, "HasAssociationType", P::reference, P::form},
    {259, "HasFamilyRelationship", P::reference, P::none},
    {261, "HasParentRelationship", P::reference, P::none},
    {262, "IsWarningAbout", P::form, P::none},
    {263, "IsWeaponOut", P::none, P::none},
    {264, "HasSpell", P::form, P::none},
    {265, "IsTimePassing", P::none, P::none},
    {266, "IsPleasant", P::none, P::none},
    {267, "IsCloudy", P::none, P::none},
    {274, "IsSmallBump", P::none, P::none},
    {277, "GetBaseActorValue", P::integer, P::none},
    {278, "IsOwner", P::form, P::none},
    {280, "IsCellOwner", P::form, P::form},
    {282, "IsHorseStolen", P::none, P::none},
    {285, "IsLeftUp", P::none, P::none},
    {286, "IsSneaking", P::none, P::none},
    {287, "IsRunning", P::none, P::none},
    {288, "GetFriendHit", P::none, P::none},
    {289, "IsInCombat", P::integer, P::none},
    {300, "IsInInterior", P::none, P::none},
    {304, "IsWaterObject", P::none, P::none},
    {305, "GetPlayerAction", P::none, P::none},
    {306, "IsActorUsingATorch", P::none, P::none},
    {309, "IsXBox", P::none, P::none},
    {310, "GetInWorldspace", P::form, P::none},
    {312, "GetPCMiscStat", P::integer, P::none},
    {313, "GetPairedAnimation", P::none, P::none},
    {314, "IsActorAVictim", P::none, P::none},
    {315, "GetTotalPersuasionNumber", P::none, P::none},
    {318, "GetIdleDoneOnce", P::none, P::none},
    {320, "GetNoRumors", P::none, P::none},
    {323, "GetCombatState", P::none, P::none},
    {325, "GetWithinPackageLocation", P::package_data, P::none},
    {327, "IsRidingMount", P::none, P::none},
    {329, "IsFleeing", P::none, P::none},
    {332, "IsInDangerousWater", P::none, P::none},
    {338, "GetIgnoreFriendlyHits", P::none, P::none},
    {339, "IsPlayersLastRiddenMount", P::none, P::none},
    {353, "IsActor", P::none, P::none},
    {354, "IsEssential", P::none, P::none},
    {358, "IsPlayerMovingIntoNewSpace", P::none, P::none},
    {359, "GetInCurrentLoc", P::form, P::none},
    {360, "GetInCurrentLocAlias", P::alias, P::none},
    {361, "GetTimeDead", P::none, P::none},
    {362, "HasLinkedRef", P::form, P::none},
    {365, "IsChild", P::none, P::none},
    {366, "GetStolenItemValueNoCrime", P::form, P::none},
    {367, "GetLastPlayerAction", P::none, P::none},
    {368, "IsPlayerActionActive", P::integer, P::none},
    {370, "IsTalkingActivatorActor", P::reference, P::none},
    {372, "IsInList", P::form, P::none},
    {373, "GetStolenItemValue", P::form, P::none},
    {375, "GetCrimeGoldViolent", P::form, P::none},
    {376, "GetCrimeGoldNonviolent", P::form, P::none},
    {378, "HasShout", P::form, P::none},
    {381, "GetHasNote", P::integer, P::none},
    {390, "GetHitLocation", P::none, P::none},
    {391, "IsPC1stPerson", P::none, P::none},
    {396, "GetCauseofDeath", P::none, P::none},
    {397, "IsLimbGone", P::integer, P::none},
    {398, "IsWeaponInList", P::form, P::none},
    {402, "IsBribedbyPlayer", P::none, P::none},
    {403, "GetRelationshipRank", P::reference, P::none},
    {407, "GetVATSValue", P::integer, P::integer},
    {408, "IsKiller", P::reference, P::none},
    {409, "IsKillerObject", P::form, P::none},
    {410, "GetFactionCombatReaction", P::form, P::form},
    {414, "Exists", P::reference, P::none},
    {415, "GetGroupMemberCount", P::none, P::none},
    {416, "GetGroupTargetCount", P::none, P::none},
    {426, "GetIsVoiceType", P::form, P::none},
    {427, "GetPlantedExplosive", P::none, P::none},
    {429, "IsScenePackageRunning", P::none, P::none},
    {430, "GetHealthPercentage", P::none, P::none},
    {432, "GetIsObjectType", P::integer, P::none},
    {434, "GetDialogueEmotion", P::none, P::none},
    {435, "GetDialogueEmotionValue", P::none, P::none},
    {437, "GetIsCreatureType", P::integer, P::none},
    {444, "GetInCurrentLocFormList", P::form, P::none},
    {445, "GetInZone", P::form, P::none},
    {446, "GetVelocity", P::integer, P::none},
    {447, "GetGraphVariableFloat", P::string, P::none},
    {448, "HasPerk", P::form, P::integer},
    {449, "GetFactionRelation", P::reference, P::none},
    {450, "IsLastIdlePlayed", P::form, P::none},
    {453, "GetPlayerTeammate", P::none, P::none},
    {454, "GetPlayerTeammateCount", P::none, P::none},
    {458, "GetActorCrimePlayerEnemy", P::none, P::none},
    {459, "GetCrimeGold", P::form, P::none},
    {463, "IsPlayerGrabbedRef", P::reference, P::none},
    {465, "GetKeywordItemCount", P::form, P::none},
    {470, "GetDestructionStage", P::none, P::none},
    {473, "GetIsAlignment", P::integer, P::none},
    {476, "IsProtected", P::none, P::none},
    {477, "GetThreatRatio", P::reference, P::none},
    {479, "GetIsUsedItemEquipType", P::form, P::none},
    {487, "IsCarryable", P::none, P::none},
    {488, "GetConcussed", P::none, P::none},
    {491, "GetMapMarkerVisible", P::none, P::none},
    {493, "PlayerKnows", P::form, P::none},
    {494, "GetPermanentActorValue", P::integer, P::none},
    {495, "GetKillingBlowLimb", P::none, P::none},
    {497, "CanPayCrimeGold", P::none, P::none},
    {499, "GetDaysInJail", P::none, P::none},
    {500, "EPAlchemyGetMakingPoison", P::none, P::none},
    {501, "EPAlchemyEffectHasKeyword", P::form, P::none},
    {503, "GetAllowWorldInteractions", P::none, P::none},
    {508, "GetLastHitCritical", P::none, P::none},
    {513, "IsCombatTarget", P::reference, P::none},
    {515, "GetVATSRightAreaFree", P::reference, P::none},
    {516, "GetVATSLeftAreaFree", P::reference, P::none},
    {517, "GetVATSBackAreaFree", P::reference, P::none},
    {518, "GetVATSFrontAreaFree", P::reference, P::none},
    {519, "GetLockIsBroken", P::none, P::none},
    {520, "IsPS3", P::none, P::none},
    {521, "IsWin32", P::none, P::none},
    {522, "GetVATSRightTargetVisible", P::reference, P::none},
    {523, "GetVATSLeftTargetVisible", P::reference, P::none},
    {524, "GetVATSBackTargetVisible", P::reference, P::none},
    {525, "GetVATSFrontTargetVisible", P::reference, P::none},
    {528, "IsInCriticalStage", P::integer, P::none},
    {530, "GetXPForNextLevel", P::none, P::none},
    {533, "GetInfamy", P::form, P::none},
    {534, "GetInfamyViolent", P::form, P::none},
    {535, "GetInfamyNonViolent", P::form, P::none},
    {543, "GetQuestCompleted", P::form, P::none},
    {547, "IsGoreDisabled", P::none, P::none},
    {550, "IsSceneActionComplete", P::form, P::integer},
    {552, "GetSpellUsageNum", P::form, P::none},
    {554, "GetActorsInHigh", P::none, P::none},
    {555, "HasLoaded3D", P::none, P::none},
    {560, "HasKeyword", P::form, P::none},
    {561, "HasRefType", P::form, P::none},
    {562, "LocationHasKeyword", P::form, P::none},
    {563, "LocationHasRefType", P::form, P::none},
    {565, "GetIsEditorLocation", P::form, P::none},
    {566, "GetIsAliasRef", P::alias, P::none},
    {567, "GetIsEditorLocAlias", P::alias, P::none},
    {568, "IsSprinting", P::none, P::none},
    {569, "IsBlocking", P::none, P::none},
    {570, "HasEquippedSpell", P::integer, P::none},
    {571, "GetCurrentCastingType", P::integer, P::none},
    {572, "GetCurrentDeliveryType", P::integer, P::none},
    {574, "GetAttackState", P::none, P::none},
    {576, "GetEventData", P::event, P::form},
    {577, "IsCloserToAThanB", P::reference, P::reference},
    {579, "GetEquippedShout", P::form, P::none},
    {580, "IsBleedingOut", P::none, P::none},
    {584, "GetRelativeAngle", P::reference, P::integer},
    {589, "GetMovementDirection", P::none, P::none},
    {590, "IsInScene", P::none, P::none},
    {591, "GetRefTypeDeadCount", P::form, P::form},
    {592, "GetRefTypeAliveCount", P::form, P::form},
    {594, "GetIsFlying", P::none, P::none},
    {595, "IsCurrentSpell", P::form, P::integer},
    {596, "SpellHasKeyword", P::integer, P::form},
    {597, "GetEquippedItemType", P::integer, P::none},
    {598, "GetLocationAliasCleared", P::alias, P::none},
    {600, "GetLocAliasRefTypeDeadCount", P::alias, P::form},
    {601, "GetLocAliasRefTypeAliveCount", P::alias, P::form},
    {602, "IsWardState", P::integer, P::none},
    {603, "IsInSameCurrentLocAsRef", P::reference, P::form},
    {604, "IsInSameCurrentLocAsRefAlias", P::alias, P::form},
    {605, "LocAliasIsLocation", P::alias, P::form},
    {606, "GetKeywordDataForLocation", P::form, P::form},
    {608, "GetKeywordDataForAlias", P::alias, P::form},
    {610, "LocAliasHasKeyword", P::alias, P::form},
    {611, "IsNullPackageData", P::package_data, P::none},
    {612, "GetNumericPackageData", P::integer, P::none},
    {613, "IsFurnitureAnimType", P::integer, P::none},
    {614, "IsFurnitureEntryType", P::integer, P::none},
    {615, "GetHighestRelationshipRank", P::none, P::none},
    {616, "GetLowestRelationshipRank", P::none, P::none},
    {617, "HasAssociationTypeAny", P::form, P::none},
    {618, "HasFamilyRelationshipAny", P::none, P::none},
    {619, "GetPathingTargetOffset", P::integer, P::none},
    {620, "GetPathingTargetAngleOffset", P::integer, P::none},
    {621, "GetPathingTargetSpeed", P::none, P::none},
    {622, "GetPathingTargetSpeedAngle", P::integer, P::none},
    {623, "GetMovementSpeed", P::none, P::none},
    {624, "GetInContainer", P::reference, P::none},
    {625, "IsLocationLoaded", P::form, P::none},
    {626, "IsLocAliasLoaded", P::alias, P::none},
    {627, "IsDualCasting", P::none, P::none},
    {629, "GetVMQuestVariable", P::form, P::string},
    {630, "GetVMScriptVariable", P::reference, P::string},
    {631, "IsEnteringInteractionQuick", P::none, P::none},
    {632, "IsCasting", P::none, P::none},
    {633, "GetFlyingState", P::none, P::none},
    {635, "IsInFavorState", P::none, P::none},
    {636, "HasTwoHandedWeaponEquipped", P::none, P::none},
    {637, "IsExitingInstant", P::none, P::none},
    {638, "IsInFriendStateWithPlayer", P::none, P::none},
    {639, "GetWithinDistance", P::reference, P::floating},
    {640, "GetActorValuePercent", P::integer, P::none},
    {641, "IsUnique", P::none, P::none},
    {642, "GetLastBumpDirection", P::none, P::none},
    {644, "IsInFurnitureState", P::integer, P::none},
    {645, "GetIsInjured", P::none, P::none},
    {646, "GetIsCrashLandRequest", P::none, P::none},
    {647, "GetIsHastyLandRequest", P::none, P::none},
    {650, "IsLinkedTo", P::reference, P::form},
    {651, "GetKeywordDataForCurrentLocation", P::form, P::none},
    {652, "GetInSharedCrimeFaction", P::reference, P::none},
    {654, "GetBribeSuccess", P::none, P::none},
    {655, "GetIntimidateSuccess", P::none, P::none},
    {656, "GetArrestedState", P::none, P::none},
    {657, "GetArrestingActor", P::none, P::none},
    {659, "EPTemperingItemIsEnchanted", P::none, P::none},
    {660, "EPTemperingItemHasKeyword", P::form, P::none},
    {664, "GetReplacedItemType", P::integer, P::none},
    {672, "IsAttacking", P::none, P::none},
    {673, "IsPowerAttacking", P::none, P::none},
    {674, "IsLastHostileActor", P::none, P::none},
    {675, "GetGraphVariableInt", P::string, P::none},
    {676, "GetCurrentShoutVariation", P::none, P::none},
    {678, "ShouldAttackKill", P::reference, P::none},
    {680, "GetActivatorHeight", P::none, P::none},
    {681, "EPMagic_IsAdvanceSkill", P::integer, P::none},
    {682, "WornHasKeyword", P::form, P::none},
    {683, "GetPathingCurrentSpeed", P::none, P::none},
    {684, "GetPathingCurrentSpeedAngle", P::integer, P::none},
    {691, "EPModSkillUsage_AdvanceObjectHasKeyword", P::form, P::none},
    {692, "EPModSkillUsage_IsAdvanceAction", P::integer, P::none},
    {693, "EPMagic_SpellHasKeyword", P::form, P::none},
    {694, "GetNoBleedoutRecovery", P::none, P::none},
    {696, "EPMagic_SpellHasSkill", P::integer, P::none},
    {697, "IsAttackType", P::form, P::none},
    {698, "IsAllowedToFly", P::none, P::none},
    {699, "HasMagicEffectKeyword", P::form, P::none},
    {700, "IsCommandedActor", P::none, P::none},
    {701, "IsStaggered", P::none, P::none},
    {702, "IsRecoiling", P::none, P::none},
    {703, "IsExitingInteractionQuick", P::none, P::none},
    {704, "IsPathing", P::none, P::none},
    {705, "GetShouldHelp", P::reference, P::none},
    {706, "HasBoundWeaponEquipped", P::integer, P::none},
    {707, "GetCombatTargetHasKeyword", P::form, P::none},
    {709, "GetCombatGroupMemberCount", P::none, P::none},
    {710, "IsIgnoringCombat", P::none, P::none},
    {711, "GetLightLevel", P::none, P::none},
    {713, "SpellHasCastingPerk", P::form, P::none},
    {714, "IsBeingRidden", P::none, P::none},
    {715, "IsUndead", P::none, P::none},
    {716, "GetRealHoursPassed", P::none, P::none},
    {718, "IsUnlockedDoor", P::none, P::none},
    {719, "IsHostileToActor", P::reference, P::none},
    {720, "GetTargetHeight", P::reference, P::none},
    {721, "IsPoison", P::none, P::none},
    {722, "WornApparelHasKeywordCount", P::form, P::none},
    {723, "GetItemHealthPercent", P::none, P::none},
    {724, "EffectWasDualCast", P::none, P::none},
    {725, "GetKnockedStateEnum", P::none, P::none},
    {726, "DoesNotExist", P::none, P::none},
    {730, "IsOnFlyingMount", P::none, P::none},
    {731, "CanFlyHere", P::none, P::none},
    {732, "IsFlyingMountPatrolQueud", P::none, P::none},
    {733, "IsFlyingMountFastTravelling", P::none, P::none},
    {734, "IsOverEncumbered", P::none, P::none},
    {735, "GetActorWarmth", P::none, P::none},
    {1024, "GetSKSEVersion", P::none, P::none},
    {1025, "GetSKSEVersionMinor", P::none, P::none},
    {1026, "GetSKSEVersionBeta", P::none, P::none},
    {1027, "GetSKSERelease", P::none, P::none},
    {1028, "ClearInvalidRegistrations", P::none, P::none},
};

} // namespace

const ConditionFunction* condition_function(std::uint16_t index) noexcept {
    const auto* end = std::end(k_functions);
    const auto* found = std::lower_bound(
        std::begin(k_functions), end, index,
        [](const ConditionFunction& f, std::uint16_t i) { return f.index < i; });
    return found != end && found->index == index ? found : nullptr;
}

ConditionParam condition_param(const Condition& c, int n) noexcept {
    const auto* f = condition_function(c.function);
    if (f == nullptr) {
        return P::none;
    }
    const P kind = n == 1 ? f->param1 : f->param2;
    if (kind == P::reference || kind == P::package) {
        if ((c.type & Condition::k_use_aliases) != 0) {
            return P::alias;
        }
        if ((c.type & Condition::k_use_package_data) != 0) {
            return P::package_data;
        }
    }
    return kind;
}

bool condition_param_is_form(const Condition& c, int n) noexcept {
    const P kind = condition_param(c, n);
    return kind == P::reference || kind == P::package || kind == P::form;
}

bool read_ctda_field(std::vector<Condition>& out, std::uint32_t& declared_count,
                     const FieldHeader& field, io::SpanReader& body,
                     std::optional<io::ParseError>& failure) {
    if (field.type == FourCC{"CTDA"}) {
        Condition c;
        take(failure, body.get<std::uint8_t>(), c.type);
        skip_bytes(failure, body, 3);
        if ((c.type & Condition::k_use_global) != 0) {
            take(failure, read_formid(body), c.value_global);
        } else {
            take(failure, body.get<float>(), c.value);
        }
        take(failure, body.get<std::uint16_t>(), c.function);
        skip_bytes(failure, body, 2);
        take(failure, body.get<std::uint32_t>(), c.param1);
        take(failure, body.get<std::uint32_t>(), c.param2);
        take(failure, body.get<std::uint32_t>(), c.run_on);
        take(failure, read_formid(body), c.reference);
        take(failure, body.get<std::int32_t>(), c.param3);
        if (!failure) {
            out.push_back(std::move(c));
        }
        return true;
    }
    if (field.type == FourCC{"CIS1"} || field.type == FourCC{"CIS2"}) {
        std::string text;
        take(failure, read_zstring(body), text);
        if (failure) {
            return true;
        }
        if (out.empty()) {
            failure = body.fail(io::ErrorKind::bad_value,
                                field.type.to_string() + " before any CTDA").error();
            return true;
        }
        (field.type == FourCC{"CIS1"} ? out.back().string1 : out.back().string2) = std::move(text);
        return true;
    }
    if (field.type == FourCC{"CITC"}) {
        take(failure, body.get<std::uint32_t>(), declared_count);
        return true;
    }
    return false;
}

} // namespace bethconv::record
