// SPDX-License-Identifier: GPL-3.0-or-later
//
// Load-order tests for three rules whose obvious version is wrong:
//
//   * The ESL flag comes from the header, not the filename (234 of 612 real
//     plugins are light, three are named .esl).
//   * The listed order is the load order. Sorting masters first breaks modern
//     lists, so build() must not do it.
//   * A FormID's high byte indexes the plugin's own master list; one past the
//     end means the plugin itself.
#include "bethconv/record/load_order.hpp"

#include "../support/esm_builder.hpp"
#include "../support/temp_dir.hpp"

#include <catch2/catch_test_macros.hpp>

#include <fstream>

using namespace bethconv::record;
using bethconv::test::TempDir;

namespace {

constexpr std::uint32_t k_flag_master = 0x0000'0001;
constexpr std::uint32_t k_flag_localized = 0x0000'0080;
constexpr std::uint32_t k_flag_light = 0x0000'0200;

/// A plugin consisting only of a TES4 header; the load order reads nothing else.
void make_plugin(const TempDir& dir, std::string_view name, std::uint32_t flags,
                 const std::vector<std::string>& masters = {}) {
    bethconv::test::ByteWriter w;
    bethconv::test::write_tes4(w, flags, masters);
    const auto path = dir / name;
    std::ofstream out(path, std::ios::binary);
    for (const auto b : w.bytes()) {
        out.put(static_cast<char>(b));
    }
}

PluginList listed(const std::vector<std::string>& names, bool marks_active = false) {
    PluginList list;
    for (const auto& name : names) {
        list.plugins.push_back(ListedPlugin{.name = name, .active = true});
    }
    list.marks_active = marks_active;
    return list;
}

/// Options without implicit-master handling, which most tests do not need.
LoadOrderOptions plain() {
    return LoadOrderOptions{.active_only = true, .add_implicit_masters = false};
}

} // namespace

// ---- the list files --------------------------------------------------------

TEST_CASE("a plugins.txt is read the way Mod Organizer writes one", "[loadorder]") {
    // BOM, CRLF, a comment, an inactive entry and stray whitespace, all taken
    // from a real file.
    const auto list = parse_plugin_list("\xEF\xBB\xBF"
                                        "# This file was automatically generated by Mod Organizer.\r\n"
                                        "*Skyrim.esm\r\n"
                                        "\r\n"
                                        "*Unofficial Skyrim Special Edition Patch.esp\r\n"
                                        "  Cathedral - 3D Tundra Grass.esp  \r\n");
    REQUIRE(list.marks_active);
    REQUIRE(list.plugins.size() == 3);
    CHECK(list.plugins[0].name == "Skyrim.esm");
    CHECK(list.plugins[0].active);
    CHECK(list.plugins[1].name == "Unofficial Skyrim Special Edition Patch.esp");
    CHECK(list.plugins[2].name == "Cathedral - 3D Tundra Grass.esp");
    CHECK_FALSE(list.plugins[2].active);
}

TEST_CASE("a loadorder.txt marks nothing, so everything counts", "[loadorder]") {
    // Same shape as plugins.txt; read as one, nothing would be active.
    const auto list = parse_plugin_list("# generated\nSkyrim.esm\nUpdate.esm\n");
    CHECK_FALSE(list.marks_active);
    REQUIRE(list.plugins.size() == 2);
    CHECK(list.plugins[0].active);
    CHECK(list.plugins[1].active);
}

TEST_CASE("a lone asterisk is not a plugin", "[loadorder]") {
    const auto list = parse_plugin_list("*\n*  \nSkyrim.esm\n");
    REQUIRE(list.plugins.size() == 1);
    CHECK(list.plugins[0].name == "Skyrim.esm");
}

// ---- placement -------------------------------------------------------------

TEST_CASE("the ESL flag comes from the header, never from the extension",
          "[loadorder]") {
    // Both cases, as in vanilla SE: a flagged .esl, and flagged .esp files.
    const TempDir dir;
    make_plugin(dir, "Heavy.esm", k_flag_master);
    make_plugin(dir, "NotActuallyLight.esl", k_flag_master); // .esl, no flag
    make_plugin(dir, "Light.esp", k_flag_light);             // .esp, flagged
    make_plugin(dir, "Plain.esp", 0);

    const auto order = LoadOrder::build(
        dir.path(), listed({"Heavy.esm", "NotActuallyLight.esl", "Light.esp", "Plain.esp"}),
        plain());
    REQUIRE(order.entries().size() == 4);
    CHECK(order.problems().empty());

    CHECK_FALSE(order.entries()[1].is_light);
    CHECK(order.entries()[2].is_light);
    CHECK(order.normal_count() == 3);
    CHECK(order.light_count() == 1);

    // The light plugin gets a slot in the 0xFE space, not a normal one.
    CHECK(order.entries()[0].index == 0);
    CHECK(order.entries()[1].index == 1);
    CHECK(order.entries()[2].index == 0); // FE:000
    CHECK(order.entries()[3].index == 2);
    CHECK(order.entries()[2].form_prefix() == 0xFE00'0000);
    CHECK(order.entries()[3].form_prefix() == 0x0200'0000);
}

TEST_CASE("the listed order is kept, and a master out of place is reported",
          "[loadorder]") {
    // Like DynDOLOD.esm: an ESM that depends on an ESP. Sorting masters first
    // would break it, so the order stays and the problem is reported.
    const TempDir dir;
    make_plugin(dir, "Base.esm", k_flag_master);
    make_plugin(dir, "Patch.esp", 0, {"Base.esm"});
    make_plugin(dir, "Late.esm", k_flag_master, {"Base.esm", "Patch.esp"});

    const auto order =
        LoadOrder::build(dir.path(), listed({"Base.esm", "Patch.esp", "Late.esm"}), plain());
    REQUIRE(order.entries().size() == 3);
    CHECK(order.entries()[0].name == "Base.esm");
    CHECK(order.entries()[1].name == "Patch.esp");
    CHECK(order.entries()[2].name == "Late.esm");
    CHECK(order.problems().empty());

    // The same three in masters-first order.
    const auto sorted =
        LoadOrder::build(dir.path(), listed({"Base.esm", "Late.esm", "Patch.esp"}), plain());
    REQUIRE(sorted.problems().size() == 1);
    CHECK(sorted.problems()[0].kind == LoadOrderProblem::Kind::master_after_dependent);
    CHECK(sorted.problems()[0].plugin == "Late.esm");
}

TEST_CASE("a missing master is a problem, not a refusal", "[loadorder]") {
    const TempDir dir;
    make_plugin(dir, "Orphan.esp", 0, {"Gone.esm"});

    const auto order = LoadOrder::build(dir.path(), listed({"Orphan.esp"}), plain());
    REQUIRE(order.entries().size() == 1);
    REQUIRE(order.problems().size() == 1);
    CHECK(order.problems()[0].kind == LoadOrderProblem::Kind::missing_master);
}

TEST_CASE("a plugin the folder does not have is reported and skipped",
          "[loadorder]") {
    const TempDir dir;
    make_plugin(dir, "Here.esm", k_flag_master);

    const auto order = LoadOrder::build(dir.path(), listed({"Here.esm", "Absent.esp"}), plain());
    CHECK(order.entries().size() == 1);
    REQUIRE(order.problems().size() == 1);
    CHECK(order.problems()[0].kind == LoadOrderProblem::Kind::not_found);
}

TEST_CASE("a name listed twice is placed once", "[loadorder]") {
    const TempDir dir;
    make_plugin(dir, "Once.esm", k_flag_master);

    const auto order =
        LoadOrder::build(dir.path(), listed({"Once.esm", "ONCE.ESM"}), plain());
    CHECK(order.entries().size() == 1);
    REQUIRE(order.problems().size() == 1);
    CHECK(order.problems()[0].kind == LoadOrderProblem::Kind::duplicate);
}

TEST_CASE("names are matched the way Windows matches them", "[loadorder]") {
    const TempDir dir;
    make_plugin(dir, "MixedCase.esm", k_flag_master);

    const auto order = LoadOrder::build(dir.path(), listed({"mixedcase.ESM"}), plain());
    REQUIRE(order.entries().size() == 1);
    CHECK(order.find("MIXEDCASE.esm").has_value());
    CHECK_FALSE(order.find("other.esm").has_value());
}

TEST_CASE("inactive plugins are dropped only when the list marks activity",
          "[loadorder]") {
    const TempDir dir;
    make_plugin(dir, "On.esm", k_flag_master);
    make_plugin(dir, "Off.esp", 0);

    PluginList marked;
    marked.marks_active = true;
    marked.plugins.push_back(ListedPlugin{.name = "On.esm", .active = true});
    marked.plugins.push_back(ListedPlugin{.name = "Off.esp", .active = false});

    CHECK(LoadOrder::build(dir.path(), marked, plain()).entries().size() == 1);

    LoadOrderOptions keep = plain();
    keep.active_only = false;
    CHECK(LoadOrder::build(dir.path(), marked, keep).entries().size() == 2);

    // The same entries from a loadorder.txt, which has no markers.
    const auto unmarked = LoadOrder::build(dir.path(), listed({"On.esm", "Off.esp"}), plain());
    CHECK(unmarked.entries().size() == 2);
}

TEST_CASE("the implicit masters go first, and only once", "[loadorder]") {
    // MO2 omits them from plugins.txt; the game loads them anyway.
    const TempDir dir;
    make_plugin(dir, "Skyrim.esm", k_flag_master);
    make_plugin(dir, "Dawnguard.esm", k_flag_master, {"Skyrim.esm"});
    make_plugin(dir, "Mod.esp", 0, {"Skyrim.esm"});

    LoadOrderOptions options;
    options.add_implicit_masters = true;
    const auto order = LoadOrder::build(dir.path(), listed({"Mod.esp"}), options);
    REQUIRE(order.entries().size() == 3);
    CHECK(order.entries()[0].name == "Skyrim.esm");
    CHECK(order.entries()[1].name == "Dawnguard.esm");
    CHECK(order.entries()[2].name == "Mod.esp");
    CHECK(order.problems().empty());

    // The other implicit masters are absent here, which is fine: one list
    // serves LE, SE and VR.
    const auto listed_too =
        LoadOrder::build(dir.path(), listed({"Skyrim.esm", "Mod.esp"}), options);
    REQUIRE(listed_too.entries().size() == 3);
    CHECK(listed_too.entries()[0].name == "Skyrim.esm");
}

TEST_CASE("a bare folder is ordered masters first, then oldest first",
          "[loadorder]") {
    const TempDir dir;
    make_plugin(dir, "Skyrim.esm", k_flag_master);
    make_plugin(dir, "Younger.esm", k_flag_master, {"Skyrim.esm"});
    make_plugin(dir, "Older.esp", 0, {"Skyrim.esm"});
    make_plugin(dir, "Newest.esp", 0, {"Skyrim.esm"});

    using clock = std::filesystem::file_time_type::clock;
    const auto now = clock::now();
    std::filesystem::last_write_time(dir / "Younger.esm", now);
    std::filesystem::last_write_time(dir / "Older.esp", now - std::chrono::hours(48));
    std::filesystem::last_write_time(dir / "Newest.esp", now + std::chrono::hours(1));

    const auto order = LoadOrder::from_directory(dir.path());
    REQUIRE(order.has_value());
    REQUIRE(order->entries().size() == 4);
    CHECK(order->entries()[0].name == "Skyrim.esm"); // implicit, always first
    CHECK(order->entries()[1].name == "Younger.esm");
    CHECK(order->entries()[2].name == "Older.esp");
    CHECK(order->entries()[3].name == "Newest.esp");
    CHECK(order->problems().empty());
}

// ---- the remap -------------------------------------------------------------

TEST_CASE("a FormID's high byte indexes the plugin's own master list",
          "[loadorder][formid]") {
    const TempDir dir;
    make_plugin(dir, "A.esm", k_flag_master);
    make_plugin(dir, "B.esm", k_flag_master, {"A.esm"});
    make_plugin(dir, "C.esp", 0, {"A.esm", "B.esm"});

    const auto order =
        LoadOrder::build(dir.path(), listed({"A.esm", "B.esm", "C.esp"}), plain());
    REQUIRE(order.entries().size() == 3);
    const std::size_t c = 2;

    // C's masters are A (0) and B (1); C itself is one past the end.
    CHECK(order.resolve(c, FormId{0x0000'1234})->value == 0x0000'1234); // -> A at 00
    CHECK(order.resolve(c, FormId{0x0100'1234})->value == 0x0100'1234); // -> B at 01
    CHECK(order.resolve(c, FormId{0x0200'1234})->value == 0x0200'1234); // -> C at 02
    CHECK(*order.owner_of(c, FormId{0x0000'1234}) == 0);
    CHECK(*order.owner_of(c, FormId{0x0200'1234}) == c);

    // The same object index means different records per plugin. B has one
    // master, so 0x01 is B itself.
    CHECK(order.resolve(1, FormId{0x0100'1234})->value == 0x0100'1234);
    CHECK(*order.owner_of(1, FormId{0x0100'1234}) == 1);
    CHECK(*order.owner_of(1, FormId{0x0000'1234}) == 0);
}

TEST_CASE("the index only looks like a load-order position", "[loadorder][formid]") {
    // B is second in the order but C lists it first, so 0x00 in C means B and
    // remaps to B's index.
    const TempDir dir;
    make_plugin(dir, "A.esm", k_flag_master);
    make_plugin(dir, "B.esm", k_flag_master, {"A.esm"});
    make_plugin(dir, "C.esp", 0, {"B.esm"});

    const auto order =
        LoadOrder::build(dir.path(), listed({"A.esm", "B.esm", "C.esp"}), plain());
    CHECK(*order.owner_of(2, FormId{0x0000'0800}) == 1);
    CHECK(order.resolve(2, FormId{0x0000'0800})->value == 0x0100'0800);
}

TEST_CASE("a light target is packed into the 0xFE space", "[loadorder][formid]") {
    const TempDir dir;
    make_plugin(dir, "Light.esp", k_flag_light);
    make_plugin(dir, "Other.esp", k_flag_light);
    make_plugin(dir, "User.esp", 0, {"Light.esp", "Other.esp"});

    const auto order = LoadOrder::build(
        dir.path(), listed({"Light.esp", "Other.esp", "User.esp"}), plain());
    REQUIRE(order.entries().size() == 3);
    CHECK(order.light_count() == 2);

    // 12-bit light index, 12-bit object index.
    CHECK(order.resolve(2, FormId{0x0000'0ABC})->value == 0xFE00'0ABC);
    CHECK(order.resolve(2, FormId{0x0100'0ABC})->value == 0xFE00'1ABC);
    // The referring plugin is normal, so its own records stay normal.
    CHECK(order.resolve(2, FormId{0x0200'0ABC})->value == 0x0000'0ABC);
}

TEST_CASE("an object index too wide for the light space is refused",
          "[loadorder][formid]") {
    // No light plugin among 622 real ones exceeds 0xFFF. If one does, it must
    // be rejected, not truncated into a collision.
    const TempDir dir;
    make_plugin(dir, "Light.esp", k_flag_light);
    make_plugin(dir, "User.esp", 0, {"Light.esp"});

    const auto order =
        LoadOrder::build(dir.path(), listed({"Light.esp", "User.esp"}), plain());
    const auto bad = order.resolve(1, FormId{0x0000'1ABC});
    REQUIRE_FALSE(bad.has_value());
    CHECK(bad.error().kind == bethconv::io::ErrorKind::bad_value);
}

TEST_CASE("a high byte past the master list fails instead of guessing",
          "[loadorder][formid]") {
    // Vanilla Skyrim.esm has one (GMST 0x0123C00E, index 1 without masters);
    // dirty mods have more.
    const TempDir dir;
    make_plugin(dir, "Alone.esm", k_flag_master);

    const auto order = LoadOrder::build(dir.path(), listed({"Alone.esm"}), plain());
    CHECK(order.resolve(0, FormId{0x0000'C00E}).has_value());
    const auto bad = order.resolve(0, FormId{0x0123'C00E});
    REQUIRE_FALSE(bad.has_value());
    CHECK(bad.error().kind == bethconv::io::ErrorKind::bad_value);
}

TEST_CASE("a reference through a missing master fails", "[loadorder][formid]") {
    const TempDir dir;
    make_plugin(dir, "Orphan.esp", 0, {"Gone.esm"});

    const auto order = LoadOrder::build(dir.path(), listed({"Orphan.esp"}), plain());
    REQUIRE(order.entries().size() == 1);
    CHECK_FALSE(order.resolve(0, FormId{0x0000'0800}).has_value());
    // Its own records still resolve.
    CHECK(order.resolve(0, FormId{0x0100'0800})->value == 0x0000'0800);
}

TEST_CASE("localization is read off the header too", "[loadorder]") {
    const TempDir dir;
    make_plugin(dir, "Local.esm", k_flag_master | k_flag_localized);
    const auto order = LoadOrder::build(dir.path(), listed({"Local.esm"}), plain());
    REQUIRE(order.entries().size() == 1);
    CHECK(order.entries()[0].is_localized);
    CHECK(order.entries()[0].is_master);
    CHECK_FALSE(order.entries()[0].is_light);
}
